name: flutter_survey_intercept_example
description: Example app demonstrating flutter_survey_intercept plugin
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_survey_intercept:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
