export const MonthYearFormat = 'MM/YYYY';
export const DMYFORMAT = 'DD/MM/YYYY';
export const YMDFORMAT = 'YYYY/MM/DD';
export const MDYFORMAT = 'MM/DD/YYYY';
export const FullMonthYearFormat = 'MMMM yyyy';
export const HalfMonthDateYearFormat = 'MMM DD, yyyy';
export const FullMonthDateYearFormat = 'MMMM DD, yyyy';
export const PPP = 'PPP';
export const DMY_AT_TIME_FORMAT = 'MMM DD, YYYY h:mm:ss A';
