

export const NETWORK_CONNECTION = "NETWORK_CONNECTION";
export const LOADING_PROGRESS = "LOADING_PROGRESS";
export const LOADING_ERROR = "ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

// Constant for Pulse app.
export const PULSE_PROFILE = "PULSE_PROFILE";
export const GET_PULSE = "GET_PULSE";
export const PULSE_RESPONSE_COLLECT = "PULSE_RESPONSE_COLLECT";
export const PULSE_PANEL_MEMBER = "PULSE_PANEL_MEMBER";
export const PULSE_DASHBOARD = "PULSE_DASHBOARD";
export const PULSE_ORG_VIEW = "PULSE_ORG_VIEW";

export const REVIEW_ITEMS = 'REVIEW_ITEMS';
export const REVIEW_INFO = 'REVIEW_INFO';
export const REVIEW_DATA = 'REVIEW_DATA'; // list of items
export const REVIEW_CATEGORIES = 'REVIEW_CATEGORIES'; // list of categories
export const REVIEW_FILTER_CATEGORIES = 'REVIEW_FILTER_CATEGORIES'; // Selected categories with items on selection
export const REVIEW_CATEGORY_ITEMS = 'REVIEW_CATEGORY_ITEMS'; // categories -> items
export const REVIEW_EMPLOYEE = 'REVIEW_EMPLOYEE'; // list of review employees
export const REVIEW_EMPLOYEE_NETWORK = 'REVIEW_EMPLOYEE_NETWORK'; // list of only review employees within network
export const EMPLOYEE_INFO = 'EMPLOYEE_INFO'; // selected employee
export const REVIEW_MYREVIEWS = 'REVIEW_MYREVIEWS';
export const REVIEW_MYREQUESTS = 'REVIEW_MYREQUESTS';
export const REVIEW_RECEIVED_REQUESTS = 'REVIEW_RECEIVED_REQUESTS';
export const REVIEW_MYREVIEWS_RECEIVED = 'REVIEW_MYREVIEWS_RECEIVED';
export const GOALS = 'GOALS';
export const PRAISE = 'PRAISE';
export const GOALS_N_OBJECTIVES = 'GOALS_N_OBJECTIVES';
export const PRAISE_NEW_BADGE = 'PRAISE_NEW_BADGE';
export const USER_BADGES = 'USER_BADGES';

//ASK module actions constants
export const ASKED_QUESTIONS = 'ASKED_QUESTIONS';
export const SUBMIT_QUESTION = 'SUBMIT_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const PENDING_QUESTIONS = 'PENDING_QUESTION';
export const ADD_QUESTION_RESPONSE = 'ADD_QUESTION_RESPONSE';
export const HISTORY_LIST = 'HISTORY_LIST';
export const HISTORY_REPORT = 'HISTORY_REPORT';


export const GOALS_NEW_OBJECTIVE = 'GOALS_NEW_OBJECTIVE';
export const REVIEW_COLLECT_RESPONSE = 'REVIEW_COLLECT_RESPONSE';
export const REVIEW_COLLECT_REQUEST = 'REVIEW_COLLECT_REQUEST';

export const PATH_FINDER = 'PATH_FINDER';
export const PATH_FINDER_RESULTS = 'PATH_FINDER_RESULTS';
export const PATH_FINDER_RESPONSE = 'PATH_FINDER_RESPONSE';

// Constant for Communities app.
export const COMMUNITIES_HOME = "COMMUNITIES_HOME";
export const COMMUNITIES_SURVEYS = "COMMUNITIES_SURVEYS";
export const COMMUNITIES_LEADERBOARD_THIS_MONTH = "COMMUNITIES_LEADERBOARD_THIS_MONTH";
export const COMMUNITIES_LEADERBOARD_LAST_MONTH = "COMMUNITIES_LEADERBOARD_LAST_MONTH";
export const COMMUNITIES_LEADERBOARD_ALLTIME = "COMMUNITIES_LEADERBOARD_ALLTIME";

export const COMMUNITIES_PANEL_DISCUSSION_LIST = "COMMUNITIES_PANEL_DISCUSSION_LIST";
export const COMMUNITIES_PROFILE = "COMMUNITIES_PROFILE";
export const COMMUNITIES_UPDATE_PROFILE = "COMMUNITIES_UPDATE_PROFILE";
export const COMMUNITIES_REWARDS = "COMMUNITIES_REWARDS";
export const COMMUNITIES_REDEEM_REWARDS = "COMMUNITIES_REDEEM_REWARDS";
export const COMMUNITIES_IDEA_CATEGORY_LIST = "COMMUNITIES_IDEA_CATEGORY_LIST";
export const COMMUNITIES_CAMPAIGN_IDEA_LIST = "COMMUNITIES_CAMPAIGN_IDEA_LIST";

export const COMMUNITIES_ADD_IDEA = "COMMUNITIES_ADD_IDEA";
export const COMMUNITIES_EDIT_IDEA = "COMMUNITIES_EDIT_IDEA";
export const COMMUNITIES_ADD_UPDATE_IDEA_VOTE = "COMMUNITIES_ADD_UPDATE_IDEA_VOTE";
export const COMMUNITIES_ADD_UPDATE_IDEA_FAVORITE = "COMMUNITIES_ADD_UPDATE_IDEA_FAVORITE";

export const COMMUNITIES_APPEND_IDEA_CATEGORIES = "COMMUNITIES_APPEND_IDEA_CATEGORIES";
export const COMMUNITIES_IDEA_COMMENTS = "COMMUNITIES_IDEA_COMMENTS";
export const COMMUNITIES_ADD_UPDATE_IDEA_COMMENT = "COMMUNITIES_ADD_UPDATE_IDEA_COMMENT";
export const COMMUNITIES_DELETE_IDEA_COMMENT = "COMMUNITIES_DELETE_IDEA_COMMENT";
export const COMMUNITIES_DELETE_IDEA = "COMMUNITIES_DELETE_IDEA";
export const COMMUNITIES_TOPIC_CATEGORY_LIST = "COMMUNITIES_TOPIC_CATEGORY_LIST";
export const COMMUNITIES_TOPIC_LIST = "COMMUNITIES_TOPIC_LIST";
export const COMMUNITIES_ADD_TOPIC = "COMMUNITIES_ADD_TOPIC";
export const COMMUNITIES_EDIT_TOPIC ="COMMUNITIES_EDIT_TOPIC";
export const COMMUNITIES_ADD_UPDATE_TOPIC_FAVORITE = "COMMUNITIES_ADD_UPDATE_TOPIC_FAVORITE";
export const COMMUNITIES_ADD_UPDATE_TOPIC_VOTE = "COMMUNITIES_ADD_UPDATE_TOPIC_VOTE";
export const COMMUNITIES_TOPIC_COMMENTS = "COMMUNITIES_TOPIC_COMMENTS";
export const COMMUNITIES_DELETE_TOPIC_COMMENT = "COMMUNITIES_DELETE_TOPIC_COMMENT";
export const COMMUNITIES_ADD_UPDATE_TOPIC_COMMENT = "COMMUNITIES_ADD_UPDATE_TOPIC_COMMENT";
export const COMMUNITIES_ADD_TOPIC_DOCUMENT = "COMMUNITIES_ADD_TOPIC_DOCUMENT";

export const COMMUNITIES_APPEND_TOPIC_CATEGORIES = "COMMUNITIES_APPEND_TOPIC_CATEGORIES";

export const COMMUNITIES_PANEL_MEMBER_SURVEYS = "COMMUNITIES_PANEL_MEMBER_SURVEYS";
export const COMMUNITIES_PANEL_MEMBER_DOCUMENTS = "COMMUNITIES_PANEL_MEMBER_DOCUMENTS";
export const COMMUNITIES_UPDATE_MEMBER_DOCUMENTS = "COMMUNITIES_UPDATE_MEMBER_DOCUMENTS";
export const COMMUNITIES_PANEL_EVENTS = "COMMUNITIES_PANEL_EVENTS";
export const COMMUNITIES_ACTIVITY_HISTORY_TODAY = "COMMUNITIES_ACTIVITY_HISTORY_TODAY";
export const COMMUNITIES_ACTIVITY_HISTORY_WEEK = "COMMUNITIES_ACTIVITY_HISTORY_WEEK";
export const COMMUNITIES_ACTIVITY_HISTORY_MONTH = "COMMUNITIES_ACTIVITY_HISTORY_MONTH";
export const COMMUNITIES_ACTIVITY_HISTORY_ALLTIME = "COMMUNITIES_ACTIVITY_HISTORY_ALLTIME";

export  const COMMUNITIES_LANGUAGE_LIST = "COMMUNITIES_LANGUAGE_LIST";
export  const COMMUNITIES_UPDATE_PANEL_LIST = "COMMUNITIES_UPDATE_PANEL_LIST";
export const COMMUNITIES_CHANGE_LANGUAGE = "COMMUNITIES_CHANGE_LANGUAGE";
export const COMMUNITIES_UPLOAD_LOCATION_RESPONSE_DATA = "COMMUNITIES_UPLOAD_LOCATION_RESPONSE_DATA";

export const COMMUNITIES_GET_PANEL_LOCATION_SURVEY_DATA = "COMMUNITIES_GET_PANEL_LOCATION_SURVEY_DATA";
// Constants for CX app

export const CX_DASHBOARD  = "CX_DASHBOARD";
export const CX_DETRACTOR_TICKETS_NEW = "CX_DETRACTOR_TICKETS_NEW";
export const CX_DETRACTOR_TICKETS_PENDING= "CX_DETRACTOR_TICKETS_PENDING";
export const CX_DETRACTOR_TICKETS_RESOLVED = "CX_DETRACTOR_TICKETS_RESOLVED";
export const CX_FEEDBACK_LIST = "CX_FEEDBACK_LIST";
export const CX_FEEDBACK_SELECTED = "CX_FEEDBACK_SELECTED";
export const CX_FEEDBACK_UPDATED = "CX_FEEDBACK_UPDATED";


export const UPDATE_LANGUAGE = "UPDATE_LANGUAGE";
export const LOGOUT = "LOGOUT";
