export const CX_DASHBOARD = 'CX_DASHBOARD';
export const CX_DETRACTOR_TICKETS_NEW = 'CX_DETRACTOR_TICKETS_NEW';
export const CX_DETRACTOR_TICKETS_PENDING = 'CX_DETRACTOR_TICKETS_PENDING';
export const CX_DETRACTOR_TICKETS_RESOLVED = 'CX_DETRACTOR_TICKETS_RESOLVED';
export const CX_FEEDBACK_LIST = 'CX_FEEDBACK_LIST';
export const CX_FEEDBACK_SELECTED = 'CX_FEEDBACK_SELECTED';
export const CX_FEEDBACK_UPDATED = 'CX_FEEDBACK_UPDATED';
