const dummyData = {
    items: [
        { id: 1, category_id: 1, title: 'Focus', reviewItemColor: 1 }, 
        { id: 2, category_id: 1, title: 'Transparent', reviewItemColor: 2 }, 
        { id: 3, category_id: 1, title: 'Integraty', reviewItemColor: 3 }, 
        { id: 4, category_id: 1, title: 'Kind', reviewItemColor: 4 }, 
        { id: 6, category_id: 1, title: 'Passion', reviewItemColor: 1 }, 
        { id: 5, category_id: 1, title: 'Inspiration', reviewItemColor: 2 }, 
        { id: 19, category_id: 1, title: 'Prompt', reviewItemColor: 3 }, 
        { id: 7, category_id: 1, title: 'Follows Through', reviewItemColor: 4 }, 
        { id: 8, category_id: 1, title: 'Patience', reviewItemColor: 1 }, 
        { id: 9, category_id: 1, title: 'Stoicism', reviewItemColor: 2 }, 
        { id: 17, category_id: 1, title: 'Insight', reviewItemColor: 3 }, 
        { id: 10, category_id: 1, title: 'Stamina', reviewItemColor: 4 }, 
        { id: 11, category_id: 1, title: 'Tenacity', reviewItemColor: 1 }, 
        { id: 12, category_id: 1, title: 'Wonkiness', reviewItemColor: 2 }, 
        { id: 13, category_id: 1, title: 'Authenticity', reviewItemColor: 3 }, 
        { id: 14, category_id: 1, title: 'Empowerment', reviewItemColor: 4 }, 
        { id: 15, category_id: 1, title: 'Positivity', reviewItemColor: 1 }, 
        { id: 16, category_id: 1, title: 'Persistence', reviewItemColor: 2 }, 
        { id: 18, category_id: 1, title: 'Accountablility', reviewItemColor: 3 }, 
        { id: 20, category_id: 1, title: 'Cooperation', reviewItemColor: 4 }, 
        { id: 21, category_id: 1, title: 'Courage', reviewItemColor: 1 }, 
        { id: 22, category_id: 1, title: 'Humanity', reviewItemColor: 2 }, 
        { id: 23, category_id: 1, title: 'Vision', reviewItemColor: 3 }, 
        { id: 24, category_id: 1, title: 'Honesty', reviewItemColor: 4 }, 
        { id: 25, category_id: 1, title: 'Insight', reviewItemColor: 1 },
    ],
    categories: [
        { id: 1, title: 'Leadership', nextActionPage: 3 }, //1: swipe, 2: drag, 3: grid 
        { id: 2, title: 'Hustle', nextActionPage: 1 }, 
        { id: 3, title: 'Teamwork', nextActionPage: 1 }, 
        { id: 4, title: 'Attention to Detail', nextActionPage: 1 }, 
        { id: 5, title: 'Empthy', nextActionPage: 1 }, 
        { id: 6, title: 'Discipline', nextActionPage: 1 }, 
        { id: 7, title: 'Code Quality', nextActionPage: 1 }, 
        { id: 8, title: 'Professionalism', nextActionPage: 1 }, 
        { id: 9, title: 'Resourcefullness', nextActionPage: 1 }, 
        { id: 10, title: 'Collaboration', nextActionPage: 1 }, 
        { id: 11, title: 'Technical Skills', nextActionPage: 1 }, 
        { id: 12, title: 'Trustworthy', nextActionPage: 1 }, 
    ],
    users: [
        { id: 1, name: 'Anup Surendran', title: 'VP.Engineering & Product', image: 'http://placehold.it/200x200/F5F5F5?text=Photo', network: 0 }, 
        { id: 2, name: 'John Jonson', title: 'VP.Customers', image: 'http://placehold.it/200x200/F5F5F5?text=Photo', network: 1 }, 
        { id: 3, name: 'Shrikant shindel', title: 'Direcotr, Engineering', image: 'http://placehold.it/200x200/F5F5F5?text=Photo', network: 0 }, 
        { id: 4, name: 'Andres Muguira', title: 'VP.Customers', image: 'http://placehold.it/200x200/F5F5F5?text=Photo', network: 0 }, 
        { id: 5, name: 'Aditya Bhat', title: 'VP, Sales', image: 'http://placehold.it/200x200/F5F5F5?text=Photo', network: 0 }, 
        { id: 6, name: 'Dinesh Maharjan', title: 'RN Developer', image: 'http://placehold.it/200x200/F5F5F5?text=Photo', network: 1 }, 
        { id: 7, name: 'Prabhat Cheetri', title: 'RN Developer', image: 'http://placehold.it/200x200/F5F5F5?text=Photo', network: 1 }, 
        { id: 8, name: 'Santosh Dhakal', title: 'Android Developer', image: 'http://placehold.it/200x200/F5F5F5?text=Photo', network: 1 }, 
        { id: 9, name: 'Binit KC', title: 'Product Manager', image: 'http://placehold.it/200x200/F5F5F5?text=Photo', network: 1 }, 
        { id: 10, name: 'Richan Shrestha', title: 'Executive', image: 'http://placehold.it/200x200/F5F5F5?text=Photo', network: 1 }
    ]
};

export default dummyData;
