export const SET_DASHBOARD_DATA  = 'SET_DASHBOARD_DATA';

export const SET_EMPLOYEE_PROFILE_DATA  = 'SET_EMPLOYEE_PROFILE_DATA';
export const UPDATE_EMPLOYEE_PROFILE_DATA  = 'UPDATE_EMPLOYEE_PROFILE_DATA';

export const GET_PULSE_DATA  = 'GET_PULSE_DATA';
export const SUBMIT_PULSE_RESPONSE  = 'SUBMIT_PULSE_RESPONSE';

export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';

export const GET_REVIEW_ITEMS = 'REVIEW_ITEMS';

export const GET_REVIEW_CATEGORIES = 'REVIEW_CATEGORIES';

export const GET_REVIEW_NETWORKS = 'REVIEW_NETWORKS';

export const GET_REVIEW_COMPETENCIES = 'REVIEW_COMPETENCIES';
